import { Inter } from 'next/font/google'
import './globals.css'
//콤포넌트
import Header from '@/components/Header'
import Footer from '@/components/Footer'
//띰 프로바이더
import { ThemeProvider } from '@/components/ThemeProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
        </body>
    </html>
  )
}
